<?php
// +----------------------------------------------------------------------+
// | 插件基础控制器接口
// +----------------------------------------------------------------------+
// | Author: 村长<idaITy@163.com>
// +----------------------------------------------------------------------+
// | Time: 2022年01月28日 14:49
// +----------------------------------------------------------------------+
namespace xc\addons;
use app\BaseController;

abstract class Controller extends BaseController
{
    /**
     * @desc 初始化
     * @author: yangsy
     * @time: 2022-01-28 14:50:26
    **/
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}